### ISSUE TITLE
Always defaulting to AM

### ISSUE THREAD

**Issue by donluz** [JordyMoos/clockpicker#4]
Hello.  Great work - nicely expanded on top of the original clockpicker.  The best improvement I was seeking is the ability to control the time increments (e.g. minutes). 

One issue I'm having... once a time is set into a text field and that field is clicked again to adjust the time, the pop-up clock always defaults to "AM" of the time already set.

Example:  if you set the time to "01:30 PM" and then click the box again to adjust the time, the window pops-up with the clockface and has "01:30 AM" - notice it's defaulting to "AM" instead of using whatever the field was already containing.

Any chance you could look into this?  It would be much appreciated.

**Comment by donluz** [comment]
I'm curious if this is still an active project.  If so, I'm willing to make a contribution to get this issue addressed.  Possible?

**Comment by JordyMoos** [comment]
Hey Donluz a pull request would be appreciated. I wont have time this week for adjusting  this project but i can do it next week if you need some help.

Cheers!

**Comment by donluz** [comment]
Ok, pull request complete (I think - totally new to me).  Will look forward to your response next week.

Much appreciated!

**Comment by donluz** [comment]
Oops - meant to ask one more thing... the placement of the control (pop-up)... I wonder if anything can be done to "auto-locate" based on screen location.  Initially I realize that adds complexity, but I've seen it done in other controls.  Selecting "top" or "bottom" is fine until it's off the screen.

Just a thought if it can be considered.

**Comment by donluz** [comment]
Hello again.  I am hoping to follow-up on this to learn of any updated status.  When you get a moment, please let me know.  Thank you.

**Comment by donluz** [comment]
Am I posting in the right place?  Please let me know if you are still willing to work on this project.  I did the pull request, but again I'm unsure what I'm doing with that regard.

Thank you for any assistance.

**Comment by JordyMoos** [comment]
https://github.com/JordyMoos/clockpicker/pull/6
